#!/usr/bin/env python3
"""Builds the static byninaaustin.com site into dist/ from the files already in this repo.

Nothing is copied by hand: pages/, home-gallery/, giveaway/ and custom-js/ stay the single
source of truth, and this script assembles them into real page URLs for Netlify.
Run locally with:  python3 build.py
"""
import os, re, shutil, json

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DIST = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'dist')
LIVE = 'https://www.byninaaustin.com'

# Live slug -> repo page. These pages are served directly by this site.
PAGES = {
    'shea-us-what-you-got': 'pages/shea-us-what-you-got-v2.html',
    'come-thru': 'pages/nike-come-thru.html',
    'dear-dad': 'pages/dear-dad.html',
    'monogram': 'pages/th-monogram.html',
    'seize-the-summer': 'pages/seize-the-summer-v2.html',
    'never-ever': 'pages/butterfinger-never-ever.html',
    'fathers-day-streamathon': 'pages/dear-dad-streamathon.html',
    'sponsored-by-suave': 'pages/sponsored-by-suave.html',
    'big-new-yorker': 'pages/pizza-hut-big-new-yorker.html',
    'creative-dna': 'pages/creative-dna-emboss.html',
    'about-me': 'pages/about.html',
    'commercials': 'pages/commercials-vertical.html',
    'content': 'pages/content-vertical.html',
    'experiential': 'pages/experiential-vertical.html',
    'the-footprint': 'pages/the-footprint-ebay.html',
    'silkpressconference': 'pages/silk-press-conference.html',
}

# Pages that still only exist in Squarespace. Until they are rebuilt here,
# the test site sends visitors to the live version.
SQUARESPACE_ONLY = [
    'plan-for-the-best', 'ok-v-day', 'for-your-lifes-work', 'curls-just-wanna-have-fun',
    'never-through', 'hbcu-tour', 'tiny-wins', 'people-not-profit', 'brunch-with-the-best',
    'the-85-shop', 'how-you-moto', 'wtyw',
]

MENU = ('<script>document.documentElement.classList.add("nl-project")</script>'
        '<script src="/js/sitewide-menu.js" defer></script>')

def localize(html):
    """Point links to the live domain at this site instead."""
    html = re.sub(r'https?://(?:www\.)?byninaaustin\.com/(?=["\'#?])', '/', html)
    html = re.sub(r'https?://(?:www\.)?byninaaustin\.com(?=["\'])', '/', html)
    html = re.sub(r'https?://(?:www\.)?byninaaustin\.com/', '/', html)
    return html

def as_document(html, title_fallback):
    if re.match(r'\s*<!doctype', html, re.I):
        return html
    return ('<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
            '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">\n'
            '</head>\n<body>\n' + html + '\n</body>\n</html>\n')

def add_menu(html):
    return re.sub(r'</body>', MENU + '</body>', html, count=1, flags=re.I) if re.search(r'</body>', html, re.I) else html + MENU

def write(rel, text):
    path = os.path.join(DIST, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)

def read(rel):
    with open(os.path.join(ROOT, rel), encoding='utf-8') as f:
        return f.read()

def main():
    shutil.rmtree(DIST, ignore_errors=True)
    os.makedirs(DIST)

    # Homepage: the 3D Portfolio Gallery, with its assets at /assets/.
    write('index.html', localize(read('home-gallery/index.html')).replace(
        "const SITE = '/';", "const SITE = '/';"))
    shutil.copytree(os.path.join(ROOT, 'home-gallery/assets'), os.path.join(DIST, 'assets'))

    # Case studies and core pages at their live addresses.
    for slug, src in PAGES.items():
        html = as_document(localize(read(src)), slug)
        write(f'{slug}/index.html', add_menu(html))

    # Portfolio Giveaway (keeps its own navigation).
    shutil.copytree(os.path.join(ROOT, 'giveaway'), os.path.join(DIST, 'portfolio-giveaway'),
                    ignore=shutil.ignore_patterns('README.md', 'netlify.toml'))

    # Shared scripts.
    os.makedirs(os.path.join(DIST, 'js'))
    write('js/sitewide-menu.js', localize(read('custom-js/sitewide-menu.js')))

    # Redirects: unbuilt pages go to the live Squarespace version for now.
    lines = ['# Generated by site/build.py']
    for slug in SQUARESPACE_ONLY:
        lines.append(f'/{slug}  {LIVE}/{slug}  302')
    lines.append('/home  /  301')
    write('_redirects', '\n'.join(lines) + '\n')

    # Search engines: sitemap + robots. Test address stays out of search until launch.
    urls = [''] + list(PAGES) + ['portfolio-giveaway']
    sm = ['<?xml version="1.0" encoding="UTF-8"?>',
          '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    sm += [f'  <url><loc>{LIVE}/{u}</loc></url>' for u in urls]
    sm.append('</urlset>')
    write('sitemap.xml', '\n'.join(sm) + '\n')
    launched = os.environ.get('SITE_LAUNCHED') == '1'
    write('robots.txt', ('User-agent: *\nAllow: /\n' if launched else 'User-agent: *\nDisallow: /\n')
          + f'Sitemap: {LIVE}/sitemap.xml\n')

    write('404.html', '<!doctype html><html lang="en"><head><meta charset="utf-8">'
          '<meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found</title>'
          '<style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#000;color:#fff;'
          'font:16px/1.5 Georgia,serif;text-align:center}a{color:#F5D98A}</style></head><body><main>'
          '<h1 style="font-weight:400">This page moved or doesn\'t exist.</h1>'
          '<p><a href="/">Back to the gallery</a></p></main>' + MENU + '</body></html>')

    print(json.dumps({'pages': len(PAGES) + 2, 'redirected_to_squarespace': len(SQUARESPACE_ONLY)}))

if __name__ == '__main__':
    main()
